package com.cascadesim.common.model

/**
 * Represents an event generated by the simulation.
 * Events can chain together to create cascade effects.
 */
data class Event(
    val id: String,
    val description: String,
    val severity: EventSeverity,
    val chainId: String,
    val sourceDecisionId: String? = null,
    val affectedEntityIds: List<String> = emptyList(),
    val timestamp: Long = System.currentTimeMillis()
)

/**
 * Severity levels for simulation events.
 */
enum class EventSeverity {
    LOW,
    MEDIUM,
    HIGH,
    CRITICAL,
    CATASTROPHIC
}
