package com.cascadesim.game.engine

import com.cascadesim.core.util.Result
import com.cascadesim.game.model.Decision
import com.cascadesim.game.model.DecisionType
import com.cascadesim.game.model.Event
import com.cascadesim.game.model.EventSeverity
import com.cascadesim.game.model.WorldState
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.withContext
import java.util.UUID

/**
 * Core simulation engine for CascadeSim.
 * Handles world state updates, cascade calculations, and simulation logic.
 */
class CascadeEngine {

    private var currentState: WorldState = WorldState()
    private val eventChainHistory = mutableMapOf<String, MutableList<Event>>()

    /**
     * Initializes the engine with default or provided configuration.
     */
    suspend fun initialize(): Result<Unit> = withContext(Dispatchers.Default) {
        return@withContext try {
            currentState = WorldState()
            eventChainHistory.clear()
            Result.Success(Unit)
        } catch (e: Exception) {
            Result.Error(e, "Failed to initialize cascade engine")
        }
    }

    /**
     * Processes a decision and generates cascading events.
     * Runs off the main thread using Dispatchers.Default.
     * 
     * @param decision The decision to process
     * @return List of events generated by this decision
     */
    suspend fun processDecision(decision: Decision): List<Event> = withContext(Dispatchers.Default) {
        val generatedEvents = mutableListOf<Event>()
        val chainId = UUID.randomUUID().toString()
        
        // Calculate base severity from impact score
        val baseSeverity = calculateSeverityFromImpact(decision.impactScore)
        
        // Create primary event
        val primaryEvent = Event(
            id = UUID.randomUUID().toString(),
            description = generateEventDescription(decision, baseSeverity),
            severity = baseSeverity,
            chainId = chainId,
            sourceDecisionId = decision.id,
            affectedEntityIds = decision.targetEntityId?.let { listOf(it) } ?: emptyList()
        )
        generatedEvents.add(primaryEvent)
        
        // Calculate trait modifiers and generate cascade events
        val cascadeEvents = calculateCascadeEffects(decision, primaryEvent, chainId)
        generatedEvents.addAll(cascadeEvents)
        
        // Update state
        currentState = currentState.copy(
            tickCount = currentState.tickCount + 1,
            cascades = currentState.cascades + com.cascadesim.game.model.Cascade(
                id = chainId,
                sourceEntityId = decision.targetEntityId ?: "system",
                intensity = decision.impactScore,
                affectedEntityIds = generatedEvents.flatMap { it.affectedEntityIds }
            )
        )
        
        // Store chain history
        eventChainHistory[chainId] = generatedEvents.toMutableList()
        
        generatedEvents
    }

    /**
     * Calculates cascade effects based on decision type and current world state.
     */
    private suspend fun calculateCascadeEffects(
        decision: Decision,
        primaryEvent: Event,
        chainId: String
    ): List<Event> = withContext(Dispatchers.Default) {
        val cascadeEvents = mutableListOf<Event>()
        
        // Cascade probability based on decision type and impact
        val cascadeProbability = when (decision.type) {
            DecisionType.DIPLOMATIC -> 0.3f
            DecisionType.ECONOMIC -> 0.5f
            DecisionType.MILITARY -> 0.7f
            DecisionType.SOCIAL -> 0.4f
            DecisionType.ENVIRONMENTAL -> 0.6f
            DecisionType.EMERGENCY -> 0.8f
        }
        
        // Generate secondary events if cascade occurs
        if (decision.impactScore > 0.5f && cascadeProbability > Math.random().toFloat()) {
            val secondarySeverity = calculateSecondarySeverity(primaryEvent.severity)
            if (secondarySeverity != null) {
                cascadeEvents.add(
                    Event(
                        id = UUID.randomUUID().toString(),
                        description = generateCascadeDescription(decision, secondarySeverity),
                        severity = secondarySeverity,
                        chainId = chainId,
                        sourceDecisionId = decision.id
                    )
                )
            }
        }
        
        cascadeEvents
    }

    /**
     * Converts impact score to event severity.
     */
    private fun calculateSeverityFromImpact(impactScore: Float): EventSeverity {
        return when {
            impactScore >= 0.9f -> EventSeverity.CATASTROPHIC
            impactScore >= 0.7f -> EventSeverity.CRITICAL
            impactScore >= 0.5f -> EventSeverity.HIGH
            impactScore >= 0.3f -> EventSeverity.MEDIUM
            else -> EventSeverity.LOW
        }
    }

    /**
     * Calculates secondary event severity (one level lower than primary).
     */
    private fun calculateSecondarySeverity(primary: EventSeverity): EventSeverity? {
        return when (primary) {
            EventSeverity.CATASTROPHIC -> EventSeverity.CRITICAL
            EventSeverity.CRITICAL -> EventSeverity.HIGH
            EventSeverity.HIGH -> EventSeverity.MEDIUM
            EventSeverity.MEDIUM -> EventSeverity.LOW
            EventSeverity.LOW -> null
        }
    }

    /**
     * Generates event description based on decision type.
     */
    private fun generateEventDescription(decision: Decision, severity: EventSeverity): String {
        val targetInfo = decision.targetEntityId?.let { " targeting $it" } ?: ""
        return "${decision.type} decision${targetInfo} with ${severity.name} impact"
    }

    /**
     * Generates cascade event description.
     */
    private fun generateCascadeDescription(decision: Decision, severity: EventSeverity): String {
        return "Cascade effect from ${decision.type} decision: ${severity.name} secondary impact"
    }

    /**
     * Advances the simulation by one tick.
     * @return Updated world state or error.
     */
    suspend fun tick(): Result<WorldState> = withContext(Dispatchers.Default) {
        return@withContext try {
            currentState = currentState.copy(
                tickCount = currentState.tickCount + 1
            )
            Result.Success(currentState)
        } catch (e: Exception) {
            Result.Error(e, "Simulation tick failed")
        }
    }

    /**
     * Returns the current world state.
     */
    fun getState(): WorldState = currentState

    /**
     * Resets the simulation to initial state.
     */
    suspend fun reset(): Result<Unit> = initialize()
    
    /**
     * Returns events for a specific chain.
     */
    fun getEventChain(chainId: String): List<Event> {
        return eventChainHistory[chainId]?.toList() ?: emptyList()
    }
}
